### ISSUE TITLE
Mac OS Xでの実行

### ISSUE THREAD

**Issue by kenjis** [xead/XeadModeler#5]
Macで簡単に実行させてみたかったので、試してみました。

以下の手順でMacでも一応動作しましたので、ご報告いたします。
1. Windowsでインストーラからインストールする
2. インストールされた`C:\.....\Program Files\XTEA\Modeler`フォルダをMacにコピーする

Macで
1. コピーした`Modeler/xteamdl.jar`をFinderからダブルクリックして起動する
2. ファイルを選んで開く

ただし、標準の[command]+[S]キーではファイルを保存することができないなど、操作性には少々問題が残りますが。

もし不具合など発見しましたら、また報告させていただこうと思います。

**Comment by kenjis** [comment]
再現条件が不明ですが、Modelerを起動し「ファイルを選んで開く」をクリックすると通常はファイル選択のダイアログが表示されますが、それが表示されず「X-TEA Modelerを起動中」のお茶の画像が表示されただけの状態がずっと続くことがあります。

この場合、MacのApplicationメニューからQuit Applicationするしかないようです。

何度か起動を繰り返すと正常にファイル選択のダイアログが表示されることもありますが、そうでない環境もありました。

「ファイルを選んで開く」ができない場合、「ファイルを新規作成して開く」を選択することで一旦ファイルを作成し、Modelerが起動した後に、「ファイル」メニューから「開く」を選択することで既存ファイルを開くことが可能でした。

**Comment by kenjis** [comment]
保存時にバックアップファイルを作成を選択すると、バックアップファイルのパスが

`/User/username/...\backup/projectYYYYMMDDHHMMSS.xead`

のようにパス区切り文字（`\`でなく`/`）が違うため「保存できませんでした。」となります。

**Comment by kenjis** [comment]
V1R4M30ですが、保存時にバックアップファイルを作成を選択すると以下のメッセージになり、やはり保存できないようです。

![backup-message](https://cloud.githubusercontent.com/assets/87955/15200458/003840e2-1822-11e6-8271-0c6d9e74f195.png)

以上、よろしくお願いします。

**Comment by xead** [comment]
kenjisさん

検証ありがとうございます。インストールフォルダにあるxteamdl.propertiesのbackupFolderの値のせいかもしれません。それを修正してからもう一度試してみてもらえませんか。

わたなべ

**Comment by kenjis** [comment]
ターミナルから実行してみると、以下のエラーが表示されました。

~~~
$ java -jar ./xteamdl.jar 
java.util.regex.PatternSyntaxException: Unexpected internal error near index 1
\
 ^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.compile(Pattern.java:1702)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at java.lang.String.replaceAll(String.java:2223)
	at xeadModeler.Modeler.saveFileWithCurrentFileName(Modeler.java:8459)
	at xeadModeler.Modeler.jMenuItemFileSave_actionPerformed(Modeler.java:8311)
	at xeadModeler.Modeler_jMenuItemFileSave_ActionAdapter.actionPerformed(Modeler.java:36682)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
~~~

`xteamdl.properties`には以下の設定がありました。

~~~
IOImageFolder = <CURRENT>\\images
BackupFolder = <CURRENT>\\backup
~~~

`\\`を`/`に変更してみましたが、同じく「保存できませんでした。」のメッセージでした。

**Comment by xead** [comment]
私のwin環境で実行したら同じ問題が発生しました(^^;あわてて変な修正をしてしまったようです。修正版のjarを送って検証していただきたいので、直接メールをいただけませんか。

**Comment by kenjis** [comment]
以下に修正した上で、修正版のjarでバックアップファイルが保存できたことを確認しました。

~~~
IOImageFolder = <CURRENT>/images
BackupFolder = <CURRENT>/backup
~~~
